version: '3'

services:
  web:
    build: .
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  mongo:
    image: "mongo:7.0"
    ports:
      - "27017:27017"
    command: mongod --auth
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-data:
